language: node_js
node_js:
  - "lts/*"
after_script: "cat ./coverage/lcov.info | coveralls"
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
